const EMOJI_QUIZ_DATA = [
    // --- 기존 문제 (1-20) ---
    { id: 1, emoji: "🏠 + 👩", answer: ["엄마", "어머니", "안방"], hint: "가족 중 누구일까요? (또는 집의 어디?)" },
    { id: 2, emoji: "🔥 + 💧", answer: ["온수", "따뜻한 물"], hint: "뜨거운 물" },
    { id: 3, emoji: "🧊 + 📦", answer: ["냉장고"], hint: "음식을 시원하게 보관해요" },
    { id: 4, emoji: "🐔 + 🍺", answer: ["치맥", "치킨맥주"], hint: "어른들이 좋아하는 야식 세트" },
    { id: 5, emoji: "🚶 + 🚪", answer: ["나간다", "외출", "퇴장"], hint: "문을 열고 밖으로!" },
    { id: 6, emoji: "🏫 + 🚌", answer: ["스쿨버스", "등교", "하교"], hint: "학교 갈 때 타는 차" },
    { id: 7, emoji: "🎂 + 🕯️", answer: ["생일", "생일파티", "케이크"], hint: "일 년에 한 번 있는 특별한 날" },
    { id: 8, emoji: "🌧️ + ☂️", answer: ["우산", "비"], hint: "비 올 때 필요해요" },
    { id: 9, emoji: "📺 + 🛋️", answer: ["거실", "휴식", "티비"], hint: "집에서 가족들이 모이는 곳" },
    { id: 10, emoji: "🦷 + 🪥", answer: ["양치", "치카치카", "양치질"], hint: "자기 전에 꼭 해야 해요" },
    { id: 11, emoji: "⚽ + 🥅", answer: ["골", "축구", "골인"], hint: "공을 발로 차서 넣어요" },
    { id: 12, emoji: "🍎 + 📺", answer: ["애플티비", "애플TV"], hint: "사과 회사의 방송" },
    { id: 13, emoji: "🌞 + 🕶️", answer: ["선글라스"], hint: "눈이 부실 때 써요" },
    { id: 14, emoji: "🕷️ + 🕸️", answer: ["거미", "거미줄"], hint: "다리가 8개인 친구" },
    { id: 15, emoji: "🌊 + 🏄", answer: ["서핑", "파도타기"], hint: "바다 위에서 보드를 타요" },
    { id: 16, emoji: "🐝 + 🍯", answer: ["꿀", "벌꿀"], hint: "달콤해요" },
    { id: 17, emoji: "🐰 + 🥕", answer: ["토끼"], hint: "깡충깡충 뛰는 동물" },
    { id: 18, emoji: "📕 + 🏫", answer: ["학교", "공부"], hint: "배우러 가는 곳" },
    { id: 19, emoji: "🍔 + 🍟", answer: ["햄버거", "햄버거세트"], hint: "패스트푸드" },
    { id: 20, emoji: "🎤 + 🎵", answer: ["노래", "가수", "노래방"], hint: "마이크 잡고 랄랄라" },

    // --- 음식 (21-40) ---
    { id: 21, emoji: "🌽 + 🐕", answer: ["콘독", "핫도그"], hint: "옥수수 + 개 = ?" },
    { id: 22, emoji: "🍚 + 🍰", answer: ["떡", "떡케이크"], hint: "쌀로 만든 케이크?" },
    { id: 23, emoji: "🍓 + 🥛", answer: ["딸기우유"], hint: "분홍색 맛있는 우유" },
    { id: 24, emoji: "🍫 + 🍪", answer: ["초코쿠키", "초코칩쿠키"], hint: "검은 점이 박힌 과자" },
    { id: 25, emoji: "🐟 + 🍞", answer: ["붕어빵"], hint: "겨울에 먹는 물고기 모양 빵" },
    { id: 26, emoji: "🍠 + 🍠", answer: ["고구마"], hint: "겨울 간식 (이미지에 답이?)" },
    { id: 27, emoji: "🥩 + 🔥", answer: ["바베큐", "고기구이", "스테이크"], hint: "고기를 불에 구워요" },
    { id: 28, emoji: "🍝 + 🇮🇹", answer: ["파스타", "스파게티"], hint: "이탈리아 면 요리" },
    { id: 29, emoji: "🌮 + 🇲🇽", answer: ["타코"], hint: "멕시코 음식" },
    { id: 30, emoji: "🍣 + 🇯🇵", answer: ["초밥", "스시"], hint: "일본 음식" },
    { id: 31, emoji: "🐮 + 🥛", answer: ["우유"], hint: "소에서 나와요" },
    { id: 32, emoji: "🍇 + 🍷", answer: ["포도주", "와인"], hint: "포도로 만든 술" },
    { id: 33, emoji: "🥔 + 🍟", answer: ["감자튀김"], hint: "감자를 튀겼어요" },
    { id: 34, emoji: "🥚 + 🍳", answer: ["계란후라이"], hint: "아침 반찬" },
    { id: 35, emoji: "🐓 + 🥚", answer: ["달걀", "계란"], hint: "닭이 낳았어요" },
    { id: 36, emoji: "🍌 + 🥛", answer: ["바나나우유"], hint: "노란색 우유" },
    { id: 37, emoji: "🦑 + 🥜", answer: ["오징어땅콩"], hint: "심심풀이 간식" },
    { id: 38, emoji: "🦐 + 🍤", answer: ["새우튀김"], hint: "새우 옷을 입혔어요" },
    { id: 39, emoji: "🥟 + 🥣", answer: ["만두국"], hint: "설날에 먹기도 해요 (떡국 대신)" },
    { id: 40, emoji: "☕ + 🧊", answer: ["아이스커피", "아아", "아이스아메리카노"], hint: "차가운 커피" },

    // --- 동물 & 자연 (41-60) ---
    { id: 41, emoji: "🐼 + 🎋", answer: ["판다", "팬더"], hint: "대나무를 좋아해요" },
    { id: 42, emoji: "🐸 + 🌧️", answer: ["청개구리"], hint: "비 오면 울어요" },
    { id: 43, emoji: "🦁 + 👑", answer: ["라이온킹", "사자왕"], hint: "동물의 왕" },
    { id: 44, emoji: "🐢 + 🐇", answer: ["토끼와거북이", "이솝우화"], hint: "달리기 경주" },
    { id: 45, emoji: "🐒 + 🍌", answer: ["원숭이"], hint: "바나나를 좋아해요" },
    { id: 46, emoji: "🐪 + 🌵", answer: ["낙타"], hint: "사막에 살아요" },
    { id: 47, emoji: "🐧 + ❄️", answer: ["펭귄"], hint: "남극에 살아요" },
    { id: 48, emoji: "🐍 + 🍎", answer: ["아담과이브", "뱀", "유혹"], hint: "사과를 건넨 동물" },
    { id: 49, emoji: "🦋 + 🌸", answer: ["나비"], hint: "꽃을 좋아해요" },
    { id: 50, emoji: "🦇 + 🧛", answer: ["뱀파이어", "드라큘라", "박쥐"], hint: "피를 마셔요" },
    { id: 51, emoji: "🐺 + 🌕", answer: ["늑대인간"], hint: "보름달을 보면 변해요" },
    { id: 52, emoji: "🦄 + 🌈", answer: ["유니콘"], hint: "전설의 동물" },
    { id: 53, emoji: "🦕 + 🦖", answer: ["공룡"], hint: "지금은 없어요" },
    { id: 54, emoji: "🐙 + 🦑", answer: ["해산물", "오징어문어"], hint: "다리가 많아요" },
    { id: 55, emoji: "🌱 + 🌳", answer: ["성장", "나무"], hint: "쑥쑥 자라요" },
    { id: 56, emoji: "☀️ + 🌻", answer: ["해바라기"], hint: "해를 따라가요" },
    { id: 57, emoji: "🌧️ + 🌈", answer: ["무지개"], hint: "비 온 뒤에 떠요" },
    { id: 58, emoji: "❄️ + ⛄", answer: ["눈사람"], hint: "겨울에 만들어요" },
    { id: 59, emoji: "🌊 + 🏖️", answer: ["해수욕장", "바다"], hint: "여름 휴가" },
    { id: 60, emoji: "🌋 + 🔥", answer: ["화산", "분화"], hint: "산이 불을 뿜어요" },

    // --- 속담 & 사자성어 & 넌센스 (61-90) ---
    { id: 61, emoji: "🙈 + 🙉 + 🙊", answer: ["삼불원", "예의", "원숭이"], hint: "보지도 듣지도 말하지도 말라" },
    { id: 62, emoji: "💡 + 🧠", answer: ["아이디어"], hint: "머리에 불이 탁!" },
    { id: 63, emoji: "👀 + 🍬", answer: ["눈깔사탕"], hint: "눈 + 사탕" },
    { id: 64, emoji: "🦶 + 🏐", answer: ["발야구", "족구"], hint: "발로 하는 공놀이 (축구 말고)" },
    { id: 65, emoji: "✋ + 🗑️", answer: ["손절"], hint: "손을 쓰레기통에? (관계를 끊음)" },
    { id: 66, emoji: "🔥 + 🥚", answer: ["불알"], hint: "좀 민망한 단어...?" },
    { id: 67, emoji: "🦴 + 🦴 + 🦴", answer: ["뼈대", "삼대"], hint: "뼈가 많아요" },
    { id: 68, emoji: "🐮 + 🔥", answer: ["소불고기", "불고기"], hint: "소를 불에 구우면?" },
    { id: 69, emoji: "🐷 + 🏦", answer: ["돼지저금통"], hint: "돈을 모으는 돼지" },
    { id: 70, emoji: "🤴 + 👑", answer: ["왕자", "임금님"], hint: "왕관을 쓴 사람" },
    { id: 71, emoji: "🧙‍♀️ + 🧹", answer: ["마녀", "해리포터"], hint: "빗자루 타고 날아요" },
    { id: 72, emoji: "🧞‍♂️ + 램프", answer: ["지니", "알라딘"], hint: "소원을 말해봐" },
    { id: 73, emoji: "🚪 + 💨", answer: ["문방구"], hint: "문 + 방귀(구) = ?" },
    { id: 74, emoji: "💑 + 💍", answer: ["결혼", "프로포즈"], hint: "반지를 줘요" },
    { id: 75, emoji: "👶 + 🍼", answer: ["아기", "신생아"], hint: "우유 먹는 사람" },
    { id: 76, emoji: "👵 + 🎂", answer: ["환갑", "칠순", "할머니생신"], hint: "할머니의 생일" },
    { id: 77, emoji: "🚑 + 🏥", answer: ["응급실", "병원"], hint: "아플 때 가요" },
    { id: 78, emoji: "🚓 + 👮", answer: ["경찰", "경찰서"], hint: "도둑을 잡아요" },
    { id: 79, emoji: "🚒 + 🔥", answer: ["소방관", "불끄기"], hint: "불 끄는 차" },
    { id: 80, emoji: "🚀 + 🌑", answer: ["달탐사", "우주여행"], hint: "우주로 가요" },
    { id: 81, emoji: "⌚ + 🍎", answer: ["애플워치"], hint: "사과 시계" },
    { id: 82, emoji: "📱 + 🍎", answer: ["아이폰"], hint: "사과 폰" },
    { id: 83, emoji: "💻 + 🪟", answer: ["윈도우", "마이크로소프트"], hint: "창문 컴퓨터" },
    { id: 84, emoji: "🐭 + 🎡", answer: ["디즈니랜드", "미키마우스"], hint: "쥐가 있는 놀이공원" },
    { id: 85, emoji: "🎥 + 🍿", answer: ["영화관", "극장"], hint: "팝콘 먹으며 봐요" },
    { id: 86, emoji: "🎣 + 🐟", answer: ["낚시", "강태공"], hint: "물고기를 잡아요" },
    { id: 87, emoji: "⛺ + 🔥", answer: ["캠핑", "불멍"], hint: "텐트 치고 불장난" },
    { id: 88, emoji: "🎨 + 🖌️", answer: ["그림", "화가", "미술"], hint: "붓으로 그려요" },
    { id: 89, emoji: "🎹 + 🎼", answer: ["피아노", "음악"], hint: "건반 악기" },
    { id: 90, emoji: "💃 + 🕺", answer: ["춤", "댄스", "파티"], hint: "신나게 흔들어요" },

    // --- 일상 & 사물 & 장소 (91-120) ---
    { id: 91, emoji: "🧺 + 👕", answer: ["빨래", "세탁"], hint: "옷을 깨끗하게" },
    { id: 92, emoji: "🧹 + 🏠", answer: ["청소"], hint: "집을 깨끗하게" },
    { id: 93, emoji: "🛒 + 🏪", answer: ["마트", "장보기", "편의점"], hint: "물건 사러 가요" },
    { id: 94, emoji: "🎁 + 🎄", answer: ["크리스마스", "성탄절"], hint: "겨울 최고의 휴일" },
    { id: 95, emoji: "🎃 + 👻", answer: ["할로윈"], hint: "유령의 날" },
    { id: 96, emoji: "🧧 + 🙇", answer: ["설날", "세배"], hint: "새해 복 많이 받으세요" },
    { id: 97, emoji: "✈️ + 🧳", answer: ["여행", "공항"], hint: "캐리어 끌고 떠나요" },
    { id: 98, emoji: "🚇 + 🎟️", answer: ["지하철"], hint: "표 끊고 타요" },
    { id: 99, emoji: "⛽ + 🚗", answer: ["주유소"], hint: "차 밥 주는 곳" },
    { id: 100, emoji: "📚 + 🤫", answer: ["도서관"], hint: "조용히 책 읽는 곳" },
    { id: 101, emoji: "💊 + 👩‍⚕️", answer: ["약국", "약"], hint: "아플 때 약 사러" },
    { id: 102, emoji: "📮 + 💌", answer: ["우체국", "편지"], hint: "편지 보내는 곳" },
    { id: 103, emoji: "💇 + ✂️", answer: ["미용실", "이발소"], hint: "머리 깎는 곳" },
    { id: 104, emoji: "🏋️ + 💪", answer: ["헬스장", "운동"], hint: "근육 만드는 곳" },
    { id: 105, emoji: "🏊 + 🏊‍♀️", answer: ["수영장"], hint: "물놀이 하는 곳" },
    { id: 106, emoji: "🎤 + 🎤", answer: ["노래방"], hint: "노래 부르는 방" },
    { id: 107, emoji: "☕ + 🍰", answer: ["카페", "커피숍"], hint: "커피와 디저트" },
    { id: 108, emoji: "🥩 + 🍽️", answer: ["레스토랑", "식당"], hint: "고상하게 밥 먹는 곳" },
    { id: 109, emoji: "🏫 + 🎓", answer: ["졸업", "대학교"], hint: "공부 끝!" },
    { id: 110, emoji: "🎬 + 🎬", answer: ["촬영", "영화"], hint: "레디~ 액션!" },
    { id: 111, emoji: "📷 + ✌️", answer: ["사진", "셀카"], hint: "치즈~" },
    { id: 112, emoji: "📱 + 💬", answer: ["카톡", "문자", "카카오톡"], hint: "메시지 보내기" },
    { id: 113, emoji: "⏰ + 🛌", answer: ["기상", "늦잠", "알람"], hint: "일어나야 해" },
    { id: 114, emoji: "🚿 + 🧼", answer: ["샤워", "목욕"], hint: "씻어요" },
    { id: 115, emoji: "💄 + 💋", answer: ["화장", "메이크업"], hint: "예뻐지는 시간" },
    { id: 116, emoji: "👔 + 💼", answer: ["출근", "직장인", "회사"], hint: "일하러 가요" },
    { id: 117, emoji: "🌙 + 😴", answer: ["잠", "꿈", "취침"], hint: "잘 자요" },
    { id: 118, emoji: "📅 + 🔴", answer: ["공휴일", "빨간날"], hint: "쉬는 날" },
    { id: 119, emoji: "❄️ + 🧊", answer: ["얼음", "겨울"], hint: "차가워요" },
    { id: 120, emoji: "🔥 + 🚒", answer: ["불이야", "화재"], hint: "불이 났어요" }
];
